apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro 
    desiredCapacity: 3
    ami: ami-05ecac759c81e0b0c
    privateNetworking: false
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub

  