apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true

    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub