apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: false
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
  